# WHAT IS PYTORCH?

Follow https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py.

In [1]:
from __future__ import print_function
import torch

In [2]:
torch.__version__

'1.3.0'

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[ 1.4739e-12,  4.5668e-41,  1.4739e-12],
        [ 4.5668e-41, -4.4015e-10,  4.5667e-41],
        [-4.4568e-10,  4.5667e-41, -4.4575e-10],
        [ 4.5667e-41, -4.3919e-10,  4.5667e-41],
        [-4.3919e-10,  4.5667e-41, -4.3920e-10]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8122, 0.4105, 0.4357],
        [0.2532, 0.6759, 0.6396],
        [0.6003, 0.5830, 0.7601],
        [0.0699, 0.4516, 0.5145],
        [0.1550, 0.3939, 0.0758]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.3865,  0.4776, -0.5614],
        [ 0.6971,  0.2872,  0.8745],
        [-0.0086, -0.0410, -0.2884],
        [-1.7058, -0.1488, -0.0412],
        [ 0.0421,  0.2306,  0.4843]])


In [8]:
print(x.size())

torch.Size([5, 3])


## Operations

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.3614,  0.7995, -0.2645],
        [ 0.9388,  0.4218,  1.2311],
        [ 0.6401,  0.8090,  0.0052],
        [-1.3886,  0.4821, -0.0180],
        [ 0.6724,  1.0337,  1.1158]])


In [10]:
print(torch.add(x, y))

tensor([[ 2.3614,  0.7995, -0.2645],
        [ 0.9388,  0.4218,  1.2311],
        [ 0.6401,  0.8090,  0.0052],
        [-1.3886,  0.4821, -0.0180],
        [ 0.6724,  1.0337,  1.1158]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.3614,  0.7995, -0.2645],
        [ 0.9388,  0.4218,  1.2311],
        [ 0.6401,  0.8090,  0.0052],
        [-1.3886,  0.4821, -0.0180],
        [ 0.6724,  1.0337,  1.1158]])


In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 2.3614,  0.7995, -0.2645],
        [ 0.9388,  0.4218,  1.2311],
        [ 0.6401,  0.8090,  0.0052],
        [-1.3886,  0.4821, -0.0180],
        [ 0.6724,  1.0337,  1.1158]])


In [13]:
print(x[:, 1])

tensor([ 0.4776,  0.2872, -0.0410, -0.1488,  0.2306])


In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1578])
0.1577952653169632


## Numpy Bridge

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [20]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!